name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: node:20.11.0-bookworm
        options: --user root:root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Initialisieren
        run: |
          echo "Initialisierung"
          rm -rf src __tests__ node_modules dist .extras/doc/api .extras/doc/folien/folien.html .extras/doc/projekthandbuch/html
          git clone https://github.com/myAccount/myRepo -b main .

      - name: Install Dependencies
        run: |
          apt-get update --yes
          apt-get install --no-install-recommends --yes --show-progress gcc=4:12.2.0-3 g++=4:12.2.0-3 make=4.3-4.1 python3.11-minimal=3.11.2-6 ca-certificates=20230311 curl=7.88.1-10+deb12u5 gnupg=2.2.40-1.1
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
          apt-get update
          apt-get install nodejs --no-install-recommends --yes --show-progress
          node --version
          npm i -g npm
          npm --version
          npm ci --no-fund --no-audit

      - name: Compile
        run: |
          npx tsc --version
          ./node_modules/.bin/tsc

      - name: Test, Codeanalyse, Security, Doku
        run: |
          echo "TODO: Rechnername/IP-Adresse des DB-Servers für Tests konfigurieren"
          npx eslint --version
          npm run eslint
          npm audit --omit=dev
          npx asciidoctor --version
          npm run asciidoctor
          npx asciidoctor-revealjs --version
          npm run revealjs
          npx typedoc --version
          npm run typedoc

      - name: Publish HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: Projekthandbuch
          path: .extras/doc/projekthandbuch/html/projekthandbuch.html

      - uses: actions/upload-artifact@v2
        with:
          name: Folien (reveal.js)
          path: .extras/doc/folien/folien.html

      - uses: actions/upload-artifact@v2
        with:
          name: TypeDoc
          path: .extras/doc/api/index.html

      - name: Create Zip
        run: |
          if [ -f film.zip ]; then
            rm film.zip
          fi
          zip -r film.zip dist
          echo "film.zip created"
        uses: actions/upload-artifact@v2
        with:
          name: film.zip
          path: film.zip

      - name: Docker Image bauen und veröffentlichen
        run: |
          echo "Docker-Image bauen und veröffentlichen"
          docker buildx build --tag juergenzimmermann/film:2024.04.0 .
          echo "Docker-Image gebaut"
          # TODO: Docker-Image veröffentlichen (z.B. Docker Hub oder ein privates Registry)
